name: PWA CI/CD Workflow

on:
  push:
    branches:
      - master
      - develop
      - main
      - os
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:  # Activación manual opcional

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configuración de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'  # Actualiza a una versión compatible

      - name: Instalación de dependencias
        run: yarn install

      - name: Compilación del proyecto
        run: yarn build
