name: PWA CI/CD Workflow

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      reason:
        description: 'Razón para iniciar el workflow manualmente'
        required: false

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalación de dependencias
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalación de ESLint si no está presente
        run: npm install eslint --save-dev

      - name: Ejecutar el linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalación de TestCafe si no está presente
        run: npm install testcafe --save-dev

      - name: Ejecutar pruebas unitarias
        run: npm run test -- --watchAll=false

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalación de dependencias
        run: npm ci

      - name: Compilar el proyecto
        run: npm run build

      - name: Desplegar a producción
        run: |
          echo "Aquí puedes agregar los comandos para desplegar, como subir a un servidor."
