name: PWA CI/CD Workflow

on:
  push:
    branches:
      - master
      - develop
      - main
      - os
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:  # Activación manual opcional

jobs:
  build:
    runs-on: ubuntu-latest  # Usar sistema operativo Linux

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configuración de Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.12.0'  # Versión compatible de Node.js

      - name: Instalación de dependencias con npm
        run: npm install  # Cambiado a npm

      - name: Compilación del proyecto
        run: npm run build  # Cambiado a npm

      - name: Ejecutar pruebas
        run: npm test
